

             type  ::=  "Number"

                     |  "RealNumber"

                     |  "RationalNumber"

                     |  "Integer"

                     |  "NaturalNumber"

                     ;

